### ISSUE TITLE
如果查询的地址内没有NFT，将下方的NFT栏清空，以免造成误导

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/NFT-Parser-0x01#8]

**Comment by 0xKT** [comment]
1. 根据BalanceOf(address)返回值来设置显示框，NFT数量为为0时，自动清空。
2. 如果NFT数量不为0的话，又Evidence没有绑定给NFT附加属性，显示的话就为空信息，只有图片信息，没有附件属性，这样也保留了附加属性的框架

**Comment by Dream4ever** [comment]
> 2\. 如果NFT数量不为0的话，又Evidence没有绑定给NFT附加属性，显示的话就为空信息，只有图片信息，没有附件属性，这样也保留了附加属性的框架

这一条单独开一个 issue，并且需要描述得再清晰、明白一些。 @Blockchain-Key
